// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header class=\"main\"><div x-data=\"{ tituloPagina : &#39;Principal&#39; }\"><nav><ul><li><a href=\"\" hx-get=\"/pages/home\" hx-target=\"main\" hx-swap=\"innerhtml\" x-on:click=\"tituloPagina = &#39;Principal&#39;\">Home</a></li></ul><ul><li><h1 x-text=\"tituloPagina\"></h1></li></ul><ul><li><a href=\"\" hx-get=\"/pages/produtos\" hx-target=\"main\" hx-swap=\"innerhtml\" x-on:click=\"tituloPagina = &#39;Produtos&#39;\">Produtos</a></li><li><a href=\"\" hx-get=\"/pages/tempo\" hx-target=\"main\" hx-swap=\"innerhtml\" x-on:click=\"tituloPagina = &#39;Tempo em Ita&#39;\">Tempo</a></li><li><a href=\"\" hx-get=\"/pages/sobre\" hx-target=\"main\" hx-swap=\"innerhtml\" x-on:click=\"tituloPagina = &#39;Sobre&#39;\">Sobre</a></li></ul></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
