// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ProdutoFormAdd() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-data=\"{\n        fechaForm() {\n            setTimeout(()=&gt;{\n                this.$refs.nomeInput.value = &#39;&#39;\n                this.$refs.descricaoInput.value = &#39;&#39;\n                $refs.popup.close()\n            }, 100)\n        }\n    }\"><button class=\"button\" x-on:click=\"fechaForm\"><i class=\"material-icons\">close </i></button><div class=\"btn-close-form-produto\"></div><form hx-post=\"/produto/adiciona\" hx-target=\"#lista-produtos\" hx-swap=\"innerHTML\" x-on:submit=\"fechaForm\"><div class=\"field\"><label for=\"nome\" class=\"label\">Nome</label><div class=\"control\"><input type=\"text\" class=\"input\" name=\"nome\" placeholder=\"Nome do produto\" x-ref=\"nomeInput\"></div></div><div class=\"field\"><label for=\"descricao\" class=\"label\">Descrição</label><div class=\"control\"><input type=\"text\" class=\"input\" placeholder=\"Descrição do produto\" x-ref=\"descricaoInput\"></div></div><div class=\"field is-grouped\"><div class=\"control\"><button class=\"button is-link\">Cadastra</button></div><div class=\"control\"><button class=\"button is-link is-light\">Limpa</button></div></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
