// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func ProdutosForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div x-data><button class=\"dialog__close-button\" aria-label=\"Close\" @click=\"$dispatch(&#39;fecha-form&#39;)\"><i class=\"material-icons\">close </i></button><h2 class=\"dialog__title\">Cadastra um Produto</h2><form class=\"product-form\" hx-post=\"/produtos\" hx-target=\"#produtos\" @submit=\"$dispatch(&#39;fecha-form&#39;)\"><div class=\"product-form__group\"><label for=\"product-name\" class=\"product-form__label\">Nome</label> <input type=\"text\" id=\"product-name\" class=\"product-form__input\" placeholder=\"Nome do produto...\" name=\"nome\"></div><div class=\"product-form__group\"><label for=\"product-description\" class=\"product-form__label\">Descrição</label> <textarea id=\"product-description\" class=\"product-form__textarea\" placeholder=\"Descrição do produto...\" name=\"descricao\"></textarea></div><div class=\"product-form__actions\"><button type=\"reset\" class=\"product-form__button product-form__button--cancel\">Limpa</button> <button type=\"submit\" class=\"product-form__button product-form__button--submit\">Cadastra</button></div></form></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
